"""Backward compatibility re-exports for honba.entities.

Entities are split into:
- honba.domain: Pure domain models (Bar, Instrument, Order, Position, Portfolio, etc.)
- honba.wire: Serialization and wire contracts (ADR 006)
"""

from honba.domain import (
    AggressorSide,
    Bar,
    Instrument,
    InstrumentId,
    InstrumentKind,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    Portfolio,
    Position,
    QuoteTick,
    TimeInForce,
    Trade,
    TradeTick,
)
from honba.domain import bar as bar
from honba.domain import instrument as instrument
from honba.domain import order as order
from honba.domain import portfolio as portfolio
from honba.domain import position as position
from honba.domain import tick as tick
from honba.domain import trade as trade
from honba.wire import (
    ENUMS,
    MODELS,
    SCHEMA_VERSION,
    BarAggregation,
    BarEvent,
    BarSpecification,
    Currency,
    Event,
    FilterOp,
    Message,
    MetricDefinition,
    MetricKeySpec,
    MetricPeriod,
    MetricRef,
    Order,
    OrderAccepted,
    OrderCancelled,
    OrderEvent,
    OrderFilled,
    OrderRejected,
    PositionSide,
    PriceType,
    QuoteEvent,
    ScreenerFilterGroup,
    ScreenerFilterPredicate,
    ScreenerRow,
    ScreenerScanRequest,
    ScreenerScanResponse,
    ScreenerSortSpec,
    Str,
    Timeframe,
    TradeEvent,
    UnitType,
    UnixNanos,
    ValueType,
    WireOrderSide,
    WireOrderType,
    WireTimeInForce,
    loads,
    loads_many,
)
from honba.wire import base as _wire_base
from honba.wire import screener as screener
from honba.wire import wire as wire

__all__ = [
    "ENUMS",
    "MODELS",
    "SCHEMA_VERSION",
    "AggressorSide",
    "Bar",
    "BarAggregation",
    "BarEvent",
    "BarSpecification",
    "Currency",
    "Event",
    "FilterOp",
    "Instrument",
    "InstrumentId",
    "InstrumentKind",
    "Message",
    "MetricDefinition",
    "MetricKeySpec",
    "MetricPeriod",
    "MetricRef",
    "Order",
    "OrderAccepted",
    "OrderCancelled",
    "OrderEvent",
    "OrderFilled",
    "OrderIntent",
    "OrderRejected",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "Portfolio",
    "Position",
    "PositionSide",
    "PriceType",
    "QuoteEvent",
    "QuoteTick",
    "ScreenerFilterGroup",
    "ScreenerFilterPredicate",
    "ScreenerRow",
    "ScreenerScanRequest",
    "ScreenerScanResponse",
    "ScreenerSortSpec",
    "Str",
    "TimeInForce",
    "Timeframe",
    "Trade",
    "TradeEvent",
    "TradeTick",
    "UnitType",
    "UnixNanos",
    "ValueType",
    "WireOrderSide",
    "WireOrderType",
    "WireTimeInForce",
    "_wire_base",
    "bar",
    "instrument",
    "loads",
    "loads_many",
    "order",
    "portfolio",
    "position",
    "screener",
    "tick",
    "trade",
    "wire",
]
