"""Wire models and serialization contracts (ADR 006)."""

from typing import Any

from honba.wire import wire as _wire_wire
from honba.wire.base import Str, _canonical, _Wire
from honba.wire.screener import (
    FilterOp,
    MetricDefinition,
    MetricKeySpec,
    MetricPeriod,
    MetricRef,
    ScreenerFilterGroup,
    ScreenerFilterPredicate,
    ScreenerRow,
    ScreenerScanRequest,
    ScreenerScanResponse,
    ScreenerSortSpec,
    Timeframe,
    UnitType,
    ValueType,
)
from honba.wire.wire import (
    ENUMS,
    MODELS,
    Bar,
    BarAggregation,
    BarEvent,
    BarSpecification,
    BarType,
    Currency,
    Event,
    InstrumentId,
    Message,
    Order,
    OrderAccepted,
    OrderCancelled,
    OrderCancelRequested,
    OrderEvent,
    OrderExpired,
    OrderFilled,
    OrderIntent,
    OrderPartiallyFilled,
    OrderRejected,
    Position,
    PositionSide,
    PriceType,
    QuoteEvent,
    QuoteTick,
    Trade,
    TradeEvent,
    TradeTick,
    UnixNanos,
    WireOrderSide,
    WireOrderType,
    WireTimeInForce,
    loads,
    loads_many,
)

__all__ = [
    "API_VERSION",
    "ENUMS",
    "MODELS",
    "SCHEMA_VERSION",
    "Bar",
    "BarAggregation",
    "BarEvent",
    "BarSpecification",
    "BarType",
    "Currency",
    "Event",
    "FilterOp",
    "InstrumentId",
    "Message",
    "MetricDefinition",
    "MetricKeySpec",
    "MetricPeriod",
    "MetricRef",
    "Order",
    "OrderAccepted",
    "OrderCancelRequested",
    "OrderCancelled",
    "OrderEvent",
    "OrderExpired",
    "OrderFilled",
    "OrderIntent",
    "OrderPartiallyFilled",
    "OrderRejected",
    "Position",
    "PositionSide",
    "PriceType",
    "QuoteEvent",
    "QuoteTick",
    "ScreenerFilterGroup",
    "ScreenerFilterPredicate",
    "ScreenerRow",
    "ScreenerScanRequest",
    "ScreenerScanResponse",
    "ScreenerSortSpec",
    "Str",
    "Timeframe",
    "Trade",
    "TradeEvent",
    "TradeTick",
    "UnitType",
    "UnixNanos",
    "ValueType",
    "WireOrderSide",
    "WireOrderType",
    "WireTimeInForce",
    "_Wire",
    "_canonical",
    "loads",
    "loads_many",
]


def __getattr__(name: str) -> Any:
    """Lazy native-backed constants (API_VERSION, SCHEMA_VERSION): they need the compiled extension."""
    if name in {"API_VERSION", "SCHEMA_VERSION"}:
        return getattr(_wire_wire, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
