[package]
name = "honba-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Simulation and paper execution models for Honba"

[dependencies]
honba-messages.workspace = true
honba-entities.workspace = true
honba-engine.workspace = true
thiserror.workspace = true


[dev-dependencies]
serde_json.workspace = true
