"""The generated wire stubs (honba-codegen) are valid, type-check, and are marked do-not-edit.

The stub shipped with `from: Any | None = None` in a class body (a SyntaxError) and with
`Generic[T]` but no `Generic` import or `T` definition, so it could not be read by any type
checker. Parsing and type-checking the committed file guards both.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

import honba

STUB = Path(honba.__file__).resolve().parent / "wire" / "generated" / "__init__.pyi"


def test_the_stub_lives_under_wire_generated() -> None:
    assert STUB.is_file(), STUB


def test_the_stub_carries_the_do_not_edit_header() -> None:
    head = STUB.read_text().splitlines()[:2]
    assert head[0].startswith("# Generated by honba-codegen")
    assert "DO NOT EDIT" in head[1]


def test_the_stub_parses() -> None:
    ast.parse(STUB.read_text(), filename=str(STUB))


def test_the_stub_type_checks_on_the_minimum_python() -> None:
    api = pytest.importorskip("mypy.api")
    stdout, stderr, status = api.run(
        [
            "--python-version",
            "3.10",
            "--no-incremental",
            "--config-file",
            "",
            str(STUB),
        ]
    )
    assert status == 0, stdout + stderr
