# Generated by honba-codegen from the Rust wire types.
# DO NOT EDIT: regenerate with `make pyi` instead.

from __future__ import annotations

from typing import Any, Generic, Literal, TypedDict, TypeVar

from typing_extensions import NotRequired

T = TypeVar("T")

SCHEMA_VERSION: int = 9
API_VERSION: str = "9.9.9"
CORE_VERSION: str = "<core>"

Count = int

class Holder:
    extra: Any = None
    price: float | None = None
    side: Side
    tags: list[str]
    venue: Venue | None = None
    weights: dict[str, float] | None = None

MaybeFlag = Literal["on"] | None

Range = TypedDict("Range", {"from": NotRequired[str | None], "tf": str})

class ResponseEnvelope(Generic[T]):
    api_version: str
    data: T | None = None
    error: ErrorDetail | None = None

Side = Literal["buy", "sell"]

class TickQuote(TypedDict):
    bid: NotRequired[float]
    type: Literal["quote"]

class TickTrade(TypedDict):
    px: NotRequired[float]
    type: Literal["trade"]

Tick = TickQuote | TickTrade

Venue = Literal["NSE", "BSE"]

Wrapper = Side
