// Generated by honba-codegen from the Rust wire types.
// DO NOT EDIT: regenerate with `make schema` instead.

export const SCHEMA_VERSION: number = 9;
export const API_VERSION: string = "9.9.9";

export type Count = number;

export interface Holder {
  extra?: unknown;
  price?: number | null;
  side: Side;
  tags: string[];
  venue?: Venue | null;
  weights?: Record<string, number>;
}

export type MaybeFlag = "on" | null;

export interface Range {
  from?: string | null;
  tf: string;
}

export type ResponseEnvelope = Record<string, unknown>;

export type Side = "buy" | "sell";

export type Tick = { bid?: number; type: "quote" } | { px?: number; type: "trade" };

export type Venue = "NSE" | "BSE";

export type Wrapper = Side;
