//! Rendering JSON Schema into TypeScript declarations.
//!
//! The rules that matter here are the ones that used to fail:
//!
//! - An enum renders as a **literal union**, not `any`. `schemars` emits a
//!   unit enum as `{"oneOf":[{"enum":["buy"]},{"enum":["sell"]}]}`, so a renderer
//!   that only looks for a top-level `enum` collapses every enum to `any`.
//! - `anyOf`/`oneOf` of plain types renders as a union, not `any`.
//! - An object with `additionalProperties` renders as a record, not `any`.
//!
//! Output is deterministic: types are emitted in sorted name order.

use serde_json::Value;

use crate::schemas::SchemaSet;

/// Renders the whole registry as a TypeScript module.
pub fn render(set: &SchemaSet, schema_version: u32, api_version: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by honba-codegen from the Rust wire types.\n");
    out.push_str("// DO NOT EDIT: regenerate with `make schema` instead.\n\n");
    out.push_str(&format!(
        "export const SCHEMA_VERSION: number = {schema_version};\n"
    ));
    out.push_str(&format!(
        "export const API_VERSION: string = \"{api_version}\";\n\n"
    ));

    for (name, schema) in set.iter() {
        out.push_str(&declaration(name, schema));
        out.push('\n');
    }
    out
}

/// Renders one `export type` or `export interface` declaration.
pub fn declaration(name: &str, schema: &Value) -> String {
    // An alias: the schema is a bare reference or a simple type.
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return format!("export type {name} = {};\n", type_ref(reference));
    }
    if let Some(literals) = enum_union(schema) {
        return format!("export type {name} = {literals};\n");
    }
    if schema.get("properties").is_some() {
        return interface(name, schema);
    }
    format!("export type {name} = {};\n", ts_type(schema))
}

/// Renders an object schema as an interface.
fn interface(name: &str, schema: &Value) -> String {
    let mut out = format!("export interface {name} {{\n");
    let required: Vec<String> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();

    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        for (prop, prop_schema) in props {
            let optional = if required.contains(prop) { "" } else { "?" };
            out.push_str(&format!(
                "  {}{}: {};\n",
                prop_name(prop),
                optional,
                ts_type(prop_schema)
            ));
        }
        // Index signature for a map-valued field set; omitted when the schema
        // declares `additionalProperties: false`, which is the common case.
    }
    out.push_str("}\n");
    out
}

/// Quotes a property name that is not a bare JS identifier.
fn prop_name(name: &str) -> String {
    let bare = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        && !name.starts_with(|c: char| c.is_ascii_digit());
    if bare {
        name.to_string()
    } else {
        format!("\"{name}\"")
    }
}

/// Strips a `#/...` prefix from a `$ref`.
fn type_ref(reference: &str) -> String {
    reference
        .rsplit('/')
        .next()
        .unwrap_or(reference)
        .to_string()
}

/// Returns a literal union when `schema` enumerates string values.
///
/// Handles both the plain `{"enum": [...]}` form and the `oneOf`-of-single-value
/// `enum`s that `schemars` emits for unit enums — the form that previously
/// collapsed every enum to `any`. Returns `None` when the values are not all
/// strings.
fn enum_union(schema: &Value) -> Option<String> {
    if let Some(values) = direct_enum(schema) {
        return Some(values);
    }
    for key in ["oneOf", "anyOf", "allOf"] {
        let variants = schema.get(key)?.as_array()?;
        let mut literals = Vec::new();
        for variant in variants {
            let found = direct_enum(variant)?;
            literals.extend(found.split(" | ").map(str::to_string));
        }
        if !literals.is_empty() {
            return Some(literals.join(" | "));
        }
    }
    None
}

fn direct_enum(schema: &Value) -> Option<String> {
    let values = schema.get("enum")?.as_array()?;
    let literals: Vec<String> = values
        .iter()
        .filter_map(Value::as_str)
        .map(|s| format!("\"{s}\""))
        .collect();
    if literals.is_empty() {
        None
    } else {
        Some(literals.join(" | "))
    }
}

/// Maps a JSON Schema fragment to a TypeScript type expression.
pub fn ts_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return type_ref(reference);
    }
    if let Some(literals) = enum_union(schema) {
        return literals;
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("string") => "string".to_string(),
        // u64 nanosecond timestamps exceed Number.MAX_SAFE_INTEGER (plan.md 4.2),
        // so they cross the TypeScript boundary as strings, not numbers.
        Some("integer") => "number".to_string(),
        Some("number") => "number".to_string(),
        Some("boolean") => "boolean".to_string(),
        Some("null") => "null".to_string(),
        Some("array") => {
            let item = schema
                .get("items")
                .map(ts_type)
                .unwrap_or_else(|| "unknown".to_string());
            format!("{item}[]")
        }
        Some("object") => record_or_map(schema),
        _ => {
            // `allOf` is an intersection, not a union: a single member must be
            // rendered as that member (this is how a newtype wrapper around a
            // ref arrives), and several members as an inline object shape.
            for key in ["oneOf", "anyOf", "allOf"] {
                if let Some(variants) = schema.get(key).and_then(Value::as_array) {
                    let types: Vec<String> = variants.iter().map(ts_type).collect();
                    if types.len() == 1 {
                        return types.into_iter().next().expect("one variant");
                    }
                    if !types.is_empty() {
                        return types.join(" | ");
                    }
                }
            }
            if schema.get("properties").is_some() || schema.get("additionalProperties").is_some() {
                return record_or_map(schema);
            }
            // A documented opaque value. `unknown` forces the caller to narrow
            // rather than letting them assume anything.
            "unknown".to_string()
        }
    }
}

/// An object with declared properties is a map over its value type; otherwise a
/// free-form record.
fn record_or_map(schema: &Value) -> String {
    if schema.get("properties").is_some() {
        // An inline object: name its fields rather than erasing them.
        let props = schema.get("properties").and_then(Value::as_object);
        let required: Vec<String> = schema
            .get("required")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(String::from)
                    .collect()
            })
            .unwrap_or_default();
        if let Some(props) = props {
            let fields: Vec<String> = props
                .iter()
                .map(|(name, sub)| {
                    let optional = if required.contains(name) { "" } else { "?" };
                    format!("{name}{optional}: {}", ts_type(sub))
                })
                .collect();
            return format!("{{ {} }}", fields.join("; "));
        }
    }
    match schema.get("additionalProperties") {
        Some(value) if value.is_object() || value.is_boolean() => {
            format!("Record<string, {}>", ts_type(value))
        }
        _ => "Record<string, unknown>".to_string(),
    }
}
