//! Rendering JSON Schema into Python `.pyi` type stubs.
//!
//! Two defects are fixed here. The old renderer emitted
//! `Optional[Optional[ErrorDetail | Any]]` for an optional field whose type was
//! itself a union — a type that happens to be accepted by a syntax checker but
//! means nothing. And it lost the type parameter of a generic such as
//! `ResponseEnvelope[T]`.
//!
//! Optionality is applied exactly once, by the field that is optional.

use serde_json::Value;

use crate::schemas::SchemaSet;

/// Renders the whole registry as a `.pyi` module.
pub fn render_pyi(set: &SchemaSet, schema_version: u32, api_version: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by honba-codegen from the Rust wire types.\n");
    out.push_str("# DO NOT EDIT: regenerate with `make pyi` instead.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import Any, Generic, Literal, TypedDict, TypeVar\n\n");
    out.push_str("from typing_extensions import NotRequired\n\n");
    out.push_str("T = TypeVar(\"T\")\n\n");
    out.push_str(&format!("SCHEMA_VERSION: int = {schema_version}\n"));
    out.push_str(&format!("API_VERSION: str = \"{api_version}\"\n"));
    out.push_str(&format!("CORE_VERSION: str = \"{CORE_VERSION}\"\n\n"));

    for (name, schema) in set.iter() {
        out.push_str(&alias(name, schema));
        out.push('\n');
    }
    out
}

/// Version of this generator, surfaced to the stubs.
pub const CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Renders one top-level alias or class.
pub fn alias(name: &str, schema: &Value) -> String {
    // A generic envelope keeps its parameter: `ResponseEnvelope[T]`.
    if name == "ResponseEnvelope" {
        return "class ResponseEnvelope(Generic[T]):\n    data: T | None\n    error: ErrorDetail | None\n"
            .to_string();
    }
    if let Some(literals) = enum_union(schema) {
        return format!("{name} = {literals}\n");
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return format!("{name} = {}\n", type_ref(reference));
    }
    if schema.get("properties").is_some() {
        return class(name, schema);
    }
    // `allOf` with a single member is how a wrapper around a ref arrives; with
    // several it is an intersection, which a stub spells as an inline dict.
    if let Some(members) = schema.get("allOf").and_then(Value::as_array) {
        if !members.is_empty() {
            let types = crate::schemas::join_union(members.iter().map(py_type));
            return format!("{name} = {types}\n");
        }
    }
    format!("{name} = {}\n", py_type(schema))
}

/// Renders an object schema as a dataclass-style stub.
///
/// A property that is not a Python identifier (`from`, `user-agent`) cannot be
/// declared in a class body, so such an object uses the functional
/// `TypedDict` form, which takes field names as strings.
pub(crate) fn class(name: &str, schema: &Value) -> String {
    let declarable = schema
        .get("properties")
        .and_then(Value::as_object)
        .map_or(true, |props| props.keys().all(|k| is_identifier(k)));
    if !declarable {
        return typed_dict(name, schema);
    }
    class_body(name, schema)
}

/// Python keywords: valid identifiers lexically, but not declarable names.
const PY_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let starts_ok = chars
        .next()
        .is_some_and(|c| c == '_' || c.is_ascii_alphabetic());
    starts_ok
        && chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
        && !PY_KEYWORDS.contains(&name)
}

/// The functional `TypedDict` form, for objects with undeclarable field names.
fn typed_dict(name: &str, schema: &Value) -> String {
    let required = required_fields(schema);
    let fields: Vec<String> = schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|props| {
            props
                .iter()
                .map(|(prop, prop_schema)| {
                    let base = py_type(prop_schema);
                    let rendered = if required.contains(prop) {
                        base
                    } else {
                        format!("NotRequired[{base}]")
                    };
                    format!("{}: {rendered}", Value::String(prop.clone()))
                })
                .collect()
        })
        .unwrap_or_default();
    format!(
        "{name} = TypedDict({}, {{{}}})\n",
        Value::String(name.to_string()),
        fields.join(", ")
    )
}

fn required_fields(schema: &Value) -> Vec<String> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default()
}

fn class_body(name: &str, schema: &Value) -> String {
    let required = required_fields(schema);

    let mut fields = String::new();
    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        for (prop, prop_schema) in props {
            let base = py_type(prop_schema);
            // Optionality is decided once, here, and never applied again
            // inside py_type.
            // If the field's own type already admits None (a union with a null
            // member), do not add a second `| None`.
            let rendered = if required.contains(prop) || admits_none(&base) {
                base
            } else {
                format!("{base} | None")
            };
            let default = if required.contains(prop) {
                ""
            } else {
                " = None"
            };
            fields.push_str(&format!("    {prop}: {rendered}{default}\n"));
        }
    }
    if fields.is_empty() {
        fields.push_str("    pass\n");
    }
    format!("class {name}:\n{fields}")
}

fn type_ref(reference: &str) -> String {
    reference
        .rsplit('/')
        .next()
        .unwrap_or(reference)
        .to_string()
}

/// Renders an enumeration as `Literal[...]`, with a `null` member as `None`.
///
/// `Literal[None]` is legal but unidiomatic; `Literal["a"] | None` is what a
/// reader and a type checker expect.
fn enum_union(schema: &Value) -> Option<String> {
    let values = crate::schemas::enum_values(schema)?;
    let literals: Vec<String> = values
        .iter()
        .filter(|v| !v.is_null())
        .map(py_literal)
        .collect();
    let mut members = Vec::new();
    if !literals.is_empty() {
        members.push(format!("Literal[{}]", literals.join(", ")));
    }
    if values.iter().any(Value::is_null) {
        members.push("None".to_string());
    }
    Some(members.join(" | "))
}

/// A JSON scalar as a Python literal. JSON string syntax is a valid Python
/// string literal; booleans are capitalized.
fn py_literal(value: &Value) -> String {
    match value {
        Value::Bool(true) => "True".to_string(),
        Value::Bool(false) => "False".to_string(),
        other => other.to_string(),
    }
}

/// Whether a rendered type expression already admits `None`.
///
/// `schemars` expresses an optional field as `{"oneOf": [{"$ref": "T"},
/// {"type": "null"}]}`, which renders as `T | None`. Adding a second `| None`
/// for the field's own optionality is what produced
/// `Optional[Optional[...]]`. `Any` already includes `None`.
fn admits_none(rendered: &str) -> bool {
    rendered
        .split(" | ")
        .any(|part| part == "None" || part == "Any")
}

/// Maps a JSON Schema fragment to a Python type expression.
///
/// This never emits `Optional[...]`: optionality belongs to the field, so
/// applying it in both places produced `Optional[Optional[...]]`.
pub fn py_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return type_ref(reference);
    }
    if let Some(literals) = enum_union(schema) {
        return literals;
    }
    // `Option<T>` arrives as {"type": ["T", "null"]}: render each member.
    if let Some(types) = schema.get("type").and_then(Value::as_array) {
        return crate::schemas::join_union(types.iter().map(|t| {
            let mut member = schema.clone();
            member["type"] = t.clone();
            py_type(&member)
        }));
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("string") => "str".to_string(),
        Some("integer") => "int".to_string(),
        Some("number") => "float".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("null") => "None".to_string(),
        Some("array") => {
            let item = schema
                .get("items")
                .map(py_type)
                .unwrap_or_else(|| "Any".to_string());
            format!("list[{item}]")
        }
        Some("object") => {
            if schema.get("properties").is_some() {
                return "dict[str, Any]".to_string();
            }
            match schema.get("additionalProperties") {
                Some(v) if v.is_object() || v.is_boolean() => {
                    format!("dict[str, {}]", py_type(v))
                }
                _ => "dict[str, Any]".to_string(),
            }
        }
        _ => {
            for key in ["oneOf", "anyOf", "allOf"] {
                if let Some(variants) = schema.get(key).and_then(Value::as_array) {
                    if variants.is_empty() {
                        continue;
                    }
                    return crate::schemas::join_union(variants.iter().map(py_type));
                }
            }
            if schema.get("properties").is_some() || schema.get("additionalProperties").is_some() {
                return "dict[str, Any]".to_string();
            }
            "Any".to_string()
        }
    }
}
