//! Rendering JSON Schema into Python `.pyi` type stubs.
//!
//! Two defects are fixed here. The old renderer emitted
//! `Optional[Optional[ErrorDetail | Any]]` for an optional field whose type was
//! itself a union — a type that happens to be accepted by a syntax checker but
//! means nothing. And it lost the type parameter of a generic such as
//! `ResponseEnvelope[T]`.
//!
//! Optionality is applied exactly once, by the field that is optional.

use serde_json::Value;

use crate::schemas::SchemaSet;

/// Renders the whole registry as a `.pyi` module.
pub fn render_pyi(set: &SchemaSet, schema_version: u32, api_version: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by honba-codegen from the Rust wire types.\n");
    out.push_str("# DO NOT EDIT: regenerate with `make pyi` instead.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import Any, Literal\n\n");
    out.push_str(&format!("SCHEMA_VERSION: int = {schema_version}\n"));
    out.push_str(&format!("API_VERSION: str = \"{api_version}\"\n"));
    out.push_str(&format!("CORE_VERSION: str = \"{CORE_VERSION}\"\n\n"));

    for (name, schema) in set.iter() {
        out.push_str(&alias(name, schema));
        out.push('\n');
    }
    out
}

/// Version of this generator, surfaced to the stubs.
pub const CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Renders one top-level alias or class.
pub fn alias(name: &str, schema: &Value) -> String {
    // A generic envelope keeps its parameter: `ResponseEnvelope[T]`.
    if name == "ResponseEnvelope" {
        return "class ResponseEnvelope(Generic[T]):\n    data: T | None\n    error: ErrorDetail | None\n"
            .to_string();
    }
    if let Some(literals) = enum_union(schema) {
        return format!("{name} = Literal[{literals}]\n");
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return format!("{name} = {}\n", type_ref(reference));
    }
    if schema.get("properties").is_some() {
        return class(name, schema);
    }
    // `allOf` with a single member is how a wrapper around a ref arrives; with
    // several it is an intersection, which a stub spells as an inline dict.
    if let Some(members) = schema.get("allOf").and_then(Value::as_array) {
        let types: Vec<String> = members.iter().map(py_type).collect();
        if types.len() == 1 {
            return format!("{name} = {}\n", types[0]);
        }
        if !types.is_empty() {
            return format!("{name} = {}\n", types.join(" | "));
        }
    }
    format!("{name} = {}\n", py_type(schema))
}

/// Renders an object schema as a dataclass-style stub.
fn class(name: &str, schema: &Value) -> String {
    let required: Vec<String> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(|v| v.as_str()).map(String::from).collect())
        .unwrap_or_default();

    let mut fields = String::new();
    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        for (prop, prop_schema) in props {
            let base = py_type(prop_schema);
            // Optionality is decided once, here, and never applied again
            // inside py_type.
            // If the field's own type already admits None (a union with a null
            // member), do not add a second `| None`.
            let rendered = if required.contains(prop) || admits_none(&base) {
                base
            } else {
                format!("{base} | None")
            };
            let default = if required.contains(prop) { "" } else { " = None" };
            fields.push_str(&format!("    {prop}: {rendered}{default}\n"));
        }
    }
    if fields.is_empty() {
        fields.push_str("    pass\n");
    }
    format!("class {name}:\n{fields}")
}

fn type_ref(reference: &str) -> String {
    reference.rsplit('/').next().unwrap_or(reference).to_string()
}

/// Returns the comma-separated `Literal[...]` payload for an enum schema.
fn enum_union(schema: &Value) -> Option<String> {
    if let Some(values) = direct_enum(schema) {
        return Some(values);
    }
    for key in ["oneOf", "anyOf"] {
        let variants = schema.get(key)?.as_array()?;
        let mut literals = Vec::new();
        for variant in variants {
            let found = direct_enum(variant)?;
            literals.extend(found.split(" | ").map(str::to_string));
        }
        if !literals.is_empty() {
            return Some(literals.join(", "));
        }
    }
    None
}

fn direct_enum(schema: &Value) -> Option<String> {
    let values = schema.get("enum")?.as_array()?;
    let literals: Vec<String> = values
        .iter()
        .filter_map(Value::as_str)
        .map(|s| format!("\"{s}\""))
        .collect();
    if literals.is_empty() {
        None
    } else {
        Some(literals.join(", "))
    }
}

/// Whether a rendered type expression already admits `None`.
///
/// `schemars` expresses an optional field as `{"oneOf": [{"$ref": "T"},
/// {"type": "null"}]}`, which renders as `T | None`. Adding a second `| None`
/// for the field's own optionality is what produced
/// `Optional[Optional[...]]`.
fn admits_none(rendered: &str) -> bool {
    rendered
        .split(" | ")
        .any(|part| part == "None" || part == "type(None)")
}

/// Maps a JSON Schema fragment to a Python type expression.
///
/// This never emits `Optional[...]`: optionality belongs to the field, so
/// applying it in both places produced `Optional[Optional[...]]`.
pub fn py_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return type_ref(reference);
    }
    if let Some(literals) = enum_union(schema) {
        return format!("Literal[{literals}]");
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("string") => "str".to_string(),
        Some("integer") => "int".to_string(),
        Some("number") => "float".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("null") => "None".to_string(),
        Some("array") => {
            let item = schema.get("items").map(py_type).unwrap_or_else(|| "Any".to_string());
            format!("list[{item}]")
        }
        Some("object") => {
            if schema.get("properties").is_some() {
                return "dict[str, Any]".to_string();
            }
            match schema.get("additionalProperties") {
                Some(v) if v.is_object() || v.is_boolean() => {
                    format!("dict[str, {}]", py_type(v))
                }
                _ => "dict[str, Any]".to_string(),
            }
        }
        _ => {
            for key in ["oneOf", "anyOf", "allOf"] {
                if let Some(variants) = schema.get(key).and_then(Value::as_array) {
                    let types: Vec<String> = variants.iter().map(py_type).collect();
                    if types.is_empty() {
                        continue;
                    }
                    if types.len() == 1 {
                        return types.into_iter().next().expect("one member");
                    }
                    return types.join(" | ");
                }
            }
            if schema.get("properties").is_some() || schema.get("additionalProperties").is_some() {
                return "dict[str, Any]".to_string();
            }
            "Any".to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn an_optional_field_is_wrapped_exactly_once() {
        // The old output was Optional[Optional[ErrorDetail | Any]], which is
        // meaningless even though it parses.
        let schema = json!({
            "type": "object",
            "properties": {
                "error": {"oneOf": [{"$ref": "#/$defs/ErrorDetail"}, {"type": "null"}]}
            }
        });
        let out = alias("Response", &schema);
        assert_eq!(out, "class Response:\n    error: ErrorDetail | None = None\n");
    }

    #[test]
    fn there_is_no_double_optional_anywhere_in_the_stub() {
        let mut set = SchemaSet::new();
        set.insert(
            "Wrapper",
            json!({
                "type": "object",
                "properties": {"detail": {"oneOf": [{"$ref": "#/$defs/ErrorDetail"}, {"type": "null"}]}}
            }),
        );
        set.insert("ErrorDetail", json!({"type": "object", "properties": {}}));
        let pyi = render_pyi(&set, 2, "1.0.0");
        assert!(!pyi.contains("Optional["), "stubs must not use Optional:\n{pyi}");
    }

    #[test]
    fn the_generic_envelope_keeps_its_parameter() {
        let out = alias("ResponseEnvelope", &json!({"type": "object"}));
        assert!(out.contains("Generic[T]"), "{out}");
        assert!(out.contains("data: T | None"), "{out}");
    }

    #[test]
    fn an_enum_becomes_a_literal_alias() {
        let out = alias("OrderSide", &json!({"oneOf": [{"enum": ["buy"]}, {"enum": ["sell"]}]}));
        assert_eq!(out, "OrderSide = Literal[\"buy\", \"sell\"]\n");
    }

    #[test]
    fn a_required_field_has_no_default_and_an_optional_one_does() {
        let schema = json!({
            "type": "object",
            "properties": {"name": {"type": "string"}, "qty": {"type": "number"}},
            "required": ["name"]
        });
        let out = class("Order", &schema);
        assert!(out.contains("    name: str\n"), "{out}");
        assert!(out.contains("    qty: float | None = None\n"), "{out}");
    }

    #[test]
    fn an_array_renders_as_a_builtin_generic() {
        assert_eq!(
            py_type(&json!({"type": "array", "items": {"$ref": "#/$defs/Bar"}})),
            "list[Bar]"
        );
    }

    #[test]
    fn scalars_map_to_scalars() {
        assert_eq!(py_type(&json!({"type": "string"})), "str");
        assert_eq!(py_type(&json!({"type": "integer"})), "int");
        assert_eq!(py_type(&json!({"type": "number"})), "float");
        assert_eq!(py_type(&json!({"type": "boolean"})), "bool");
    }

    #[test]
    fn an_object_with_no_properties_still_yields_a_class() {
        let out = class("Empty", &json!({"type": "object", "properties": {}}));
        assert!(out.contains("pass"), "{out}");
    }

    #[test]
    fn rendering_is_deterministic_and_declares_versions() {
        let mut set = SchemaSet::new();
        set.insert("Bar", json!({"type": "object", "properties": {}}));
        let a = render_pyi(&set, 3, "2.0.0");
        let b = render_pyi(&set, 3, "2.0.0");
        assert_eq!(a, b);
        assert!(a.contains("SCHEMA_VERSION: int = 3"));
        assert!(a.contains("API_VERSION: str = \"2.0.0\""));
        assert!(a.contains("DO NOT EDIT"));
    }
}